mod 'puppet-nginx'
mod 'puppetlabs-stdlib'
mod 'puppetlabs-concat'
mod 'puppetlabs-wsus_client'
mod 'gabe-yum_updates'
mod 'puppetlabs-service'
mod 'puppetlabs-windows'


mod 'pltraining/dockeragent'
mod 'garethr/docker'
mod 'puppetlabs/acl'
mod 'puppetlabs/chocolatey'
mod 'puppetlabs/dsc'
mod 'puppetlabs/iis'
mod 'puppetlabs/powershell'
mod 'puppetlabs/reboot'
mod 'puppetlabs/registry'
mod 'puppet/download_file'
mod 'puppet/windows_env'
mod 'puppet/windowsfeature'
